### ISSUE TITLE
Enable Glimpse support

### ISSUE THREAD

**Issue by mconta** [2sic/2SexyContent#141]
Hello, 

Glimpse is a great tool for analyzing performance on DNN, but it seems to have incompatibility with 2sic Entity Framework.

Here is the message;

Error: [Module name] is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Unfortunately we don't support using Glimpse.Ado without using Glimpse.EF when you are using EntityFramework. This is due to the way in which EntityFramework handles particular cases.

Here is what Glimpse adds to the bottom of the page when configured on a DNN server:

![image](https://cloud.githubusercontent.com/assets/2010201/6018034/f6cc526a-ab93-11e4-8187-c4b18666972c.png)

And here is the detailed view:

![image](https://cloud.githubusercontent.com/assets/2010201/6018050/1c840f5c-ab94-11e4-8f73-96c448dbf2c5.png)

Glimpse can be configured using this DNN module:

https://dnnglimpse.codeplex.com/

Here is the complete call stack:

DotNetNuke.Services.Exceptions.ModuleLoadException: Unfortunately we don't support using Glimpse.Ado without using Glimpse.EF when you are using EntityFramework. This is due to the way in which EntityFramework handles particular cases. ---> System.NotSupportedException: Unfortunately we don't support using Glimpse.Ado without using Glimpse.EF when you are using EntityFramework. This is due to the way in which EntityFramework handles particular cases.
   at Glimpse.Ado.AlternateType.GlimpseDbProviderFactory`1.GetService(Type serviceType)
   at System.Data.Common.DbProviderServices.GetProviderServices(DbProviderFactory factory)
   at System.Data.Metadata.Edm.StoreItemCollection.Loader.InitializeProviderManifest(Action`3 addError)
   at System.Data.EntityModel.SchemaObjectModel.Schema.HandleAttribute(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.SchemaElement.ParseAttribute(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.SchemaElement.Parse(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.Schema.HandleTopLevelSchemaElement(XmlReader reader)
   at System.Data.EntityModel.SchemaObjectModel.Schema.InternalParse(XmlReader sourceReader, String sourceLocation)
   at System.Data.EntityModel.SchemaObjectModel.Schema.Parse(XmlReader sourceReader, String sourceLocation)
   at System.Data.EntityModel.SchemaObjectModel.SchemaManager.ParseAndValidate(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, SchemaDataModelOption dataModel, AttributeValueNotification providerNotification, AttributeValueNotification providerManifestTokenNotification, ProviderManifestNeeded providerManifestNeeded, IList`1& schemaCollection)
   at System.Data.Metadata.Edm.StoreItemCollection.Loader.LoadItems(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths)
   at System.Data.Metadata.Edm.StoreItemCollection.Init(IEnumerable`1 xmlReaders, IEnumerable`1 filePaths, Boolean throwOnError, DbProviderManifest& providerManifest, DbProviderFactory& providerFactory, String& providerManifestToken, Memoizer`2& cachedCTypeFunction)
   at System.Data.Metadata.Edm.StoreItemCollection..ctor(IEnumerable`1 xmlReaders, IEnumerable`1 filePaths)
   at System.Data.Metadata.Edm.MetadataCache.StoreMetadataEntry.LoadStoreCollection(EdmItemCollection edmItemCollection, MetadataArtifactLoader loader)
   at System.Data.Metadata.Edm.MetadataCache.LoadItemCollection[T](IItemCollectionLoader`1 itemCollectionLoader, T entry)
   at System.Data.Metadata.Edm.MetadataCache.GetOrCreateStoreAndMappingItemCollections(String cacheKey, MetadataArtifactLoader loader, EdmItemCollection edmItemCollection, Object& entryToken)
   at System.Data.EntityClient.EntityConnection.LoadStoreItemCollections(MetadataWorkspace workspace, DbConnection storeConnection, DbProviderFactory factory, DbConnectionOptions connectionOptions, EdmItemCollection edmItemCollection, MetadataArtifactLoader artifactLoader)
   at System.Data.EntityClient.EntityConnection.GetMetadataWorkspace(Boolean initializeAllCollections)
   at System.Data.EntityClient.EntityConnection.InitializeMetadata(DbConnection newConnection, DbConnection originalConnection, Boolean closeOriginalConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at ToSic.Eav.EavContext.GetAllZones()
   at ToSic.Eav.DataSources.Caches.BaseCache.EnsureCache()
   at ToSic.Eav.DataSources.Caches.BaseCache.GetZoneAppId(Nullable`1 zoneId, Nullable`1 appId)
   at ToSic.Eav.DataSource.GetZoneAppId(Nullable`1 zoneId, Nullable`1 appId)
   at ToSic.Eav.DataSource.GetDataSource(String sourceName, Nullable`1 zoneId, Nullable`1 appId, IDataSource upstream, IConfigurationProvider configurationProvider)
   at ToSic.Eav.EavContext.InitZoneApp(Nullable`1 zoneId, Nullable`1 appId)
   at ToSic.Eav.EavContext.Instance(Nullable`1 zoneId, Nullable`1 appId)
   at ToSic.SexyContent.SexyContent..ctor(Int32 zoneId, Int32 appId, Boolean enableCaching, Nullable`1 ownerPortalId)
   at ToSic.SexyContent.SexyControlEditBase.get_Sexy()
   at ToSic.SexyContent.SexyControlEditBase.get_Elements()
   at ToSic.SexyContent.SexyControlEditBase.get_Template()
   at ToSic.SexyContent.SexyControlEditBase.get_IsList()
   at ToSic.SexyContent.SexyViewContentOrApp.get_ModuleActions()
   --- End of inner exception stack trace ---

**Comment by iJungleboy** [comment]
I've never used glimpse before, but I based on the message I understand that you need to add another component called glimpse.EF to get it to work. Did you try than?

**Comment by iJungleboy** [comment]
Hi Mateo
So I don't know glimpse, but I believe you'll have to use the correct EF-version (and 2sxc doesn't use v6!). So I'm guessing you just created a new error by adding the wrong glimpse extension. 

The reason other modules probably don't cause trouble is because many don't use Entity-Framework. The new DNN 8 is probably going to use EF7, but previously most DNN-modules used direct SQL or other types of data access like the DAL2, PetaPoco etc.

**Comment by iJungleboy** [comment]
But just so you know - if you figure this out, it would be a great blog-post for DNN :)

**Comment by mconta** [comment]
Hi  iJungleboy, 

I'm going to open an issue on the dnn glimpse project, I hope they'll help me to resolve this problem.
Glimpse is not fundamental but it adds a lot of value while investigating performance issues on dnn,

And sure, I'll make a post  as soon as I get the solution :-) 

Thank you for your (great) work and the support.

**Comment by iJungleboy** [comment]
that sounds good. and make sure you tried using the EF version that's appropriate. for example, ef6 has so many changes (mainly namespaces) that it's not compatible to previous ones...

**Comment by mconta** [comment]
Solved!!!!  (with the help of the DNN glimpse support) :sparkles:  :fireworks: 

Now 2sic modules are compatible with glimpse!!!!!!

You need to : 

* download the latest DNN glimpse from https://dnnglimpse.codeplex.com/
* install the module on DNN from HOST->Extensions
* delete from bin the dll "Glimpse.ADO.dll"
* enjoy

**Comment by iJungleboy** [comment]
awesome. 
I believe you're the second person to have issues with glimpse. Could you blog about it :)
